version: '3'

services:
   web:
        build: ./docker/webapps/.
        ports:
            - "8088:8080"
   mysql:
        image: mysql:5.6
        environment:
            MYSQL_ROOT_PASSWORD: 'secret'
        ports:
            - 3306:3306
        volumes:
        - ./docker/mysql:/docker-entrypoint-initdb.d
  
